### ISSUE TITLE
mRealSenseDevice->Init() returns -3 (PXC_STATUS_ITEM_UNAVAILABLE)

### ISSUE THREAD

**Issue by mileshiroo** [SethGibson/ofxRSSDK#2]
Hello, 

I'm trying to run example-simple with VisualStudio 2012 and OF 0.8.4. 

I get an error on line 99 of ofxRSSDK.cpp:

_Unhandled exception at 0x009888C8 in example-simple_debug.exe: 0xC0000005: Access violation reading location 0x00000000._

After printing some values, I figured out that this is because mRealSenseDevice->QueryCaptureManager()->QueryDevice() returns null. This might be related to the fact that mRealSenseDevice->Init() on line 97 returns -3, PXC_STATUS_ITEM_UNAVAILABLE.

The camera I'm using is a RealSense R200, and the R200 and common examples from the SDK sample browser work as expected.

Thanks!
Miles

**Comment by SethGibson** [comment]
Currently we haven't added support for the R200 hardware or camera manager and I don't have a timeline for this yet other than "soon". Given ofx's lack of official support for recent windows compilers, we're going to go back and retool the whole addon in the very near future, which will bring everything up to the current SDK.

**Comment by mileshiroo** [comment]
Hi Seth, thanks for the reply, that's really helpful to know. I'm going to try to get something working with the R200. I'll let you know if I do!

**Comment by obviousjim** [comment]
Hey Seth thanks for helping us out here. @mlsptn perhaps we could try the bleeding edge OF which works for VS2015?

**Comment by SethGibson** [comment]
I'm happy to take a look at that too, what do i need to get that build working? Also, off the top of my head, you could try and changing the hardcoded depth size to 480x360 or 320x240, originally I was writing this for F200, which supports higher res depth than R200.

**Comment by mileshiroo** [comment]
Hey, I just got the addon to work with the R200 by changing how the depth and color streams are enabled in the init function. [Here](https://gist.github.com/mlsptn/1cc8a80a138337e2bc9a#file-gistfile1-cpp) is the init function I have now. I also had to change the width and height to 320x240 in ofxRSSDKProvider.h.

**Comment by SethGibson** [comment]
Awesome! I'm going to lock myself to my computer this weekend and get this back to version "Usable", i'll get this branch functional first, then start working on the re-arched branch per the README notes.

**Comment by mileshiroo** [comment]
Oops, it turns out that changing width and height (to 320x240) in the header file is all that's necessary for it to work with the R200. Thank you for the help!

**Comment by obviousjim** [comment]
Yay!

On Thursday, June 4, 2015, Miles Peyton notifications@github.com wrote:

> Hey, I just got the addon to work with the R200 by changing how the depth
> and color streams are enabled in the init function. Here
> https://gist.github.com/mlsptn/1cc8a80a138337e2bc9a#file-gistfile1-cpp
> is the init function I have now. I also had to change the width and height
> to 320x240 in ofxRSSDKProvider.h.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SethGibson/ofxRSSDK/issues/2#issuecomment-108992246.

## 
- James

**Comment by SethGibson** [comment]
Yeah, i figured that was going to come back and bite me in the ass :( Rest assured the fix is (will be) in! For reference, if you need higher res depth, the R200 supports a "cropped" vga resolution of 628x468 (you lose six pixels on either side due to the particularities of the stereo matching algorithm). This will also be supported in the addon, as well as automatically handling mapping over the disparity.

**Comment by SethGibson** [comment]
Also, I'm going to leave this open until I actually fix it.

**Comment by SethGibson** [comment]
Closing as I've moved development over to ofxRSSDKv2.
